version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-budget-api
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: budgetdb
      MYSQL_USER: joao
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    build: .
    container_name: simplegoapi
    restart: always
    environment:
      - DB_USER=joao
      - DB_PASS=123456
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=budgetdb
    ports:
      - "8080:8080"
    depends_on:
      - mysql

volumes:
  mysql-data:
